# Generated by Django 5.0.2 on 2025-11-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_escolar_desit_api', '0003_alumnos_maestros'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnos',
            name='rol',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='maestros',
            name='rol',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
