# Generated by Django 5.0.2 on 2025-11-11 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_escolar_desit_api', '0004_alumnos_rol_maestros_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maestros',
            name='rol',
        ),
        migrations.AddField(
            model_name='maestros',
            name='fecha_nacimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maestros',
            name='id_trabajador',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maestros',
            name='materias_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
