# Generated by Django 5.0.2 on 2025-11-13 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_escolar_desit_api', '0005_remove_maestros_rol_maestros_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnos',
            name='fecha_nacimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumnos',
            name='matricula',
            field=models.CharField(default=0, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
