# Generated by Django 5.0.2 on 2025-11-13 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_escolar_desit_api', '0008_alter_alumnos_fecha_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnos',
            name='fecha_nacimiento',
        ),
    ]
