# Generated by Django 5.0.2 on 2025-11-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_escolar_desit_api', '0009_remove_alumnos_fecha_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnos',
            name='rol',
        ),
        migrations.AddField(
            model_name='alumnos',
            name='fecha_nacimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='matricula',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
