# Generated by Django 5.0.2 on 2025-12-01 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_escolar_desit_api', '0010_remove_alumnos_rol_alumnos_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nrc', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('section', models.CharField(max_length=20)),
                ('dia', models.CharField(max_length=80)),
                ('hora_inicio', models.TimeField()),
                ('hora_final', models.TimeField()),
                ('salon', models.CharField(max_length=50)),
                ('carrera', models.CharField(max_length=100)),
                ('creditos', models.PositiveIntegerField()),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('maestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_escolar_desit_api.maestros')),
            ],
        ),
    ]
