# Generated by Django 5.0.2 on 2025-12-01 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_escolar_desit_api', '0011_materias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materias',
            old_name='maestro',
            new_name='id_maestro',
        ),
        migrations.RenameField(
            model_name='materias',
            old_name='carrera',
            new_name='programa',
        ),
        migrations.RemoveField(
            model_name='materias',
            name='dia',
        ),
        migrations.AddField(
            model_name='materias',
            name='dias_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
